server:
  port: ${GATEWAY_PORT:8080}

spring:
  application:
    name: api-gateway

cors:
  allowed:
    # Lee la variable de entorno CORS_ALLOWED_ORIGIN
    # Si no está definida, usa http://localhost:5173 por defecto
    origin: ${CORS_ALLOWED_ORIGIN:http://localhost:5173}
management:
  endpoints:
    web:
      exposure:
        include: "*"
