server:
  port: 9000

logging:
  level:
    org.springframework.security: trace

spring:
  security:
    user:
      name: user
      password: password
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "oidc-client"
              client-secret: "secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "${CORS_ALLOWED_ORIGIN:http://localhost}/authentication/callback"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true

cors:
  allowed:
    origin: ${CORS_ALLOWED_ORIGIN:http://localhost}