server:
  port: ${SERVER_PORT:8083}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/usuarios}

#.env
#${SERVER_PORT}=8083
#${MONGODB_URI}=mongodb://localhost:27017/inventario
#${FEIGN_CLIENT_URL}=http://localhost:8082