server:
  port: ${SERVER_PORT:8082}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/pedidos}

feign:
  client:
    products:
      url: ${PRODUCT_SERVICE_URL:http://localhost:8081}
    users:
      url: ${USER_SERVICE_URL:http://localhost:8083}
